---
title: "s1-3 mRNA quantification for the data by Chang et al."
author: "Yoichiro Sugimoto"
date: "`r format(Sys.time(), '%d %B, %Y')`"
vignette: >
  %\VignetteIndexEntry{Bioconductor style for PDF documents}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
   html_document:
     highlight: haddock
     toc: yes
     toc_depth: 2
     keep_md: yes
     fig_width: 5
     fig_height: 5
---

# Overview

The abundance of mRNA in the carotid body and adrenal medulla will be quantified by `Salmon`, based on the data by Chang et al. (PMID: 26560302).


# Setup


```{r load_packages, message = FALSE, warning = FALSE}

project.dir <- "/fast/AG_Sugimoto/home/users/yoichiro/projects/20230620_Phd2KO_in_AM_and_CB"

renv::restore("/fast/AG_Sugimoto/home/users/yoichiro/projects/20230620_Phd2KO_in_AM_and_CB/R")

processors <- 7

temp <- sapply(list.files(
    file.path(project.dir, "R/functions"),
    full.names = TRUE
), source)


```

## The input and output files and the directories

```{r setup_directories}

annot.dir <- file.path(project.dir, "annotation/")
annot.mm39.dir <- file.path(annot.dir, "mm39_annotation")
annot.mm39.raw.dir <- file.path(annot.mm39.dir, "raw")
salmon.index.dir <- file.path(annot.dir, "mm39_annotation/salmon_indices/") 

fq.dir <- file.path(project.dir, "data/fastq")

results.dir <- file.path(project.dir, "results")
s0.dir <- file.path(results.dir, "s0-public-data")
s1.dir <- file.path(results.dir, "s1")


```

# Quantify mRNAs


```{r download_gtf_files}

public.sample.dt <- file.path(
    project.dir, "data/sample_data/public_data_source.csv"
) %>% fread


quantPublicmRNAs <- function(dt.idx, public.sample.dt, s0.dir, s1.dir){
    
    sample.name <- public.sample.dt[dt.idx, sample_name]

    fq <- file.path(
        s0.dir,
        paste0(sample.name, c(".fastq"))
    )
    
    salmon.dir <- file.path("/fast/AG_Sugimoto/home/users/yoichiro/software/from_source/salmon-1.9.0_linux_x86_64")


    paste(
        file.path(salmon.dir, "bin", "salmon"),
        "quant",
        "-p", processors,
        "-i", file.path(salmon.index.dir, "transcripts_index"),
        "-l", "U",
        "-r", fq,
        "--validateMappings",
        ## "--seqBias", "--gcBias", "--posBias",
        "-o", file.path(s1.dir, sample.name)
    ) %>%
        system.cat

    return()
}

lapply(
    1:nrow(public.sample.dt),
    quantPublicmRNAs,
    public.sample.dt = public.sample.dt,
    s0.dir = s0.dir,
    s1.dir = s1.dir
)

```

# Session information

```{r session_info}

sessioninfo::session_info()

```
