---
title: "sa data submission"
author: "Yoichiro Sugimoto"
date: "`r format(Sys.time(), '%d %B, %Y')`"
vignette: >
  %\VignetteIndexEntry{Bioconductor style for PDF documents}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
   html_document:
     highlight: haddock
     toc: yes
     toc_depth: 2
     keep_md: yes
     fig_width: 5
     fig_height: 5
---

# Overview

RNA-Seq data will be submitted to the database.

# Setup


```{r load_packages, message = FALSE, warning = FALSE}

project.dir <- "/fast/AG_Sugimoto/home/users/yoichiro/projects/20230620_Phd2KO_in_AM_and_CB"
renv::restore("/fast/AG_Sugimoto/home/users/yoichiro/projects/20230620_Phd2KO_in_AM_and_CB/R")

processors <- 7

temp <- sapply(list.files(
    file.path(project.dir, "R/functions"),
    full.names = TRUE
), source)

set.seed(1)

```

# Export file information 

```{r export_info}

results.dir <- file.path(project.dir, "results")
sa.dir <- file.path(results.dir, "sa")

create.dirs(c(
    sa.dir
))

fastq.dir <- file.path(project.dir, "data/fastq")

sample.dt <- fread(file.path(
    project.dir, "/data/sample_data/20210401_sample_data.csv"
))


fq.files <- file.path(
    fastq.dir,
    paste0(
        rep(sample.dt[, file_name], each = 2),
        c("_1.fastq.gz", "_2.fastq.gz")
    )
)

md5sum.dt <- tools::md5sum(
                        fq.files
                    ) %>%
    stack %>%
    data.table

md5sum.dt[, ind := basename(file.path(ind))]

md5sum.dt <- md5sum.dt[, .(ind, values)]

fwrite(
    md5sum.dt, file.path(sa.dir, "md5sum.txt"),
    sep = "\t", col.names = FALSE
)


```


# Session information

```{r session info}

sessioninfo::session_info()

```
